# Generated by Django 4.1.2 on 2022-10-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveSmallIntegerField(verbose_name='kilometraje')),
                ('description', models.CharField(max_length=200)),
                ('price', models.PositiveSmallIntegerField(verbose_name='costo')),
                ('date', models.DateField(verbose_name='Fecha ')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
    ]
